[project]
name = "charliek-github-io"
version = "0.1.0"
description = "Charlie Knudsen's project index"
requires-python = ">=3.13"

[dependency-groups]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.14",
    "pymdown-extensions>=10.15",
]
